<?php

/**
 * ADT API
 * Official & Core API for ADT  [ADT](http://adtcore.io)  Main API 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;
use App\Models\DrugModels\Drug;
class DrugsApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation drugsGet
     *
     * fetches a list of services at a facility.
     *
     *
     * @return Http response
     */
    public function drugsGet()
    {
        $response = Drug::get();
        return response()->json($response, 200);
    }
    /**
     * Operation drugsPost
     *
     * Add a new service to the facility.
     *
     *
     * @return Http response
     */
    public function drugsPost()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $body = $input['body'];


        return response('How about implementing drugsPost as a POST method ?');
    }
    /**
     * Operation drugsDrugIdDelete
     *
     * Deletes the drug specified by drugId.
     *
     * @param int $drug_id Particular Service at facility specified by the ID (required)
     *
     * @return Http response
     */
    public function drugsDrugIdDelete($drug_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing drugsDrugIdDelete as a DELETE method ?');
    }
    /**
     * Operation drugsDrugIdGet
     *
     * Find drug by drugId.
     *
     * @param int $drug_id Particular Service at facility specified by the ID (required)
     *
     * @return Http response
     */
    public function drugsDrugIdGet($drug_id)
    {
        $response = Drug::findOrFail($drug_id);
        return response()->json($response, 200);
    }
    /**
     * Operation drugsDrugIdPut
     *
     * Update an existing drug specified by the drugId.
     *
     * @param int $drug_id Particular Service at facility specified by the ID (required)
     *
     * @return Http response
     */
    public function drugsDrugIdPut($drug_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing drugsDrugIdPut as a PUT method ?');
    }
    /**
     * Operation drugsDrugIdDoseGet
     *
     * Find drug dose for drugId.
     *
     * @param int $drug_id ID of service that needs to be fetched (required)
     *
     * @return Http response
     */
    public function drugsDrugIdDoseGet($drug_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing drugsDrugIdDoseGet as a GET method ?');
    }
    /**
     * Operation drugsDrugIdDosePost
     *
     * Add a dose for a particular drug with drugId.
     *
     * @param int $drug_id ID of service that needs to be fetched (required)
     *
     * @return Http response
     */
    public function drugsDrugIdDosePost($drug_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing drugsDrugIdDosePost as a POST method ?');
    }
}