<?php

/**
 * ADT API
 * Official & Core API for ADT  [ADT](http://adtcore.io)  Main API 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class ServicesApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation servicesGet
     *
     * fetches a list of services at a facility.
     *
     *
     * @return Http response
     */
    public function servicesGet()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $limit = $input['limit'];


        return response('How about implementing servicesGet as a GET method ?');
    }
    /**
     * Operation deleteService
     *
     * Deletes a Service.
     *
     * @param int $service_id Patient id to delete (required)
     *
     * @return Http response
     */
    public function deleteService($service_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteService as a DELETE method ?');
    }
    /**
     * Operation getServiceById
     *
     * Find service by serviceId.
     *
     * @param int $service_id ID of service that needs to be fetched (required)
     *
     * @return Http response
     */
    public function getServiceById($service_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getServiceById as a GET method ?');
    }
    /**
     * Operation updateService
     *
     * Update an existing patient.
     *
     * @param int $service_id Patient id to delete (required)
     *
     * @return Http response
     */
    public function updateService($service_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing updateService as a PUT method ?');
    }
}
