<?php

/**
 * ADT API
 * Official & Core API for ADT  [ADT](http://adtcore.io)  Main API 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class UsersApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

   
    /**
     * Operation usersGet
     *
     * fetches a list of users at a facility.
     *
     *
     * @return Http response
     */
    public function usersGet()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $limit = $input['limit'];


        return response('How about implementing usersGet as a GET method ?');
    }
    /**
     * Operation usersPost
     *
     * Add a new user to the facility.
     *
     *
     * @return Http response
     */
    public function usersPost()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $body = $input['body'];


        return response('How about implementing usersPost as a POST method ?');
    }
    /**
     * Operation usersUsersIdDelete
     *
     * Deletes the drug specified by drugId.
     *
     * @param int $users_id Particular Service at facility specified by the ID (required)
     *
     * @return Http response
     */
    public function usersUsersIdDelete($users_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing usersUsersIdDelete as a DELETE method ?');
    }
    /**
     * Operation usersUsersIdGet
     *
     * Find drug by drugId.
     *
     * @param int $users_id Particular Service at facility specified by the ID (required)
     *
     * @return Http response
     */
    public function usersUsersIdGet($users_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing usersUsersIdGet as a GET method ?');
    }
    /**
     * Operation usersUsersIdPut
     *
     * Update an existing drug specified by the drugId.
     *
     * @param int $users_id Particular Service at facility specified by the ID (required)
     *
     * @return Http response
     */
    public function usersUsersIdPut($users_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing usersUsersIdPut as a PUT method ?');
    }
}